### ISSUE TITLE
missing atomix requirement

### ISSUE THREAD

**Issue by paleozogt** [opennetworkinglab/onos-kubernetes#6]
When I try to install I see an error:
```
helm install charts/onos
Error: found in requirements.yaml, but missing in charts/ directory: atomix
```

Looking in requirements I see:
```
cat charts/onos/requirements.yaml
dependencies:
- name: atomix
  version: 0.1.0
  repository: file://../../../atomix-k8s
```

The path to `atomix-k8s` is out of this project.  Where does it come from?
